force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PropertyRepository.cls
public with sharing class PropertyRepository implements IRepository{
    
    Property__c property;
    String queryString;
    
    public PropertyRepository(Property__c property, String queryString) {
        this.property = property;
        this.queryString = queryString;
    }

    public List<Object> doQuery(){
        return Database.query(this.queryString);
    }

    public Object doUpsert(){
        try {
            Database.upsert(this.property);
            return true;
        } catch (Exception e) {
            System.debug(e);
            return false; 
        }
    }

    public Object getByMunicipio(String municipio){
        String queryString = 'SELECT Id FROM Property__c WHERE Municipio__r.Name = \'' + municipio + '\'';
        return Database.query(queryString);
    }
}