force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The listed sale price of the home.</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Area__c</fullName>
    <formula>Area__c *  Length__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TotalValuePropertySalesController.cls
public with sharing class TotalValuePropertySalesController {
    
    @AuraEnabled
    public static String getPropertysByMunicipio(String idMunicipio){
        try {
            String queryString = 'SELECT Id, Name, Price__c, Total_Area__c, Cep__c FROM Property__c WHERE Municipio__c = \'' + String.escapeSingleQuotes(idMunicipio) + '\'';
            System.debug(queryString);
                List<Property__c> propertys = (List<Property__c>) new PropertyRepository(null, queryString).doQuery();
                System.debug(propertys);
                return System.JSON.serialize(propertys);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}