force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The listed sale price of the home.</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PropertyBatch.cls
public class PropertyBatch implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Account__c FROM Property__c WHERE Price__c >= 1000000';
        return Database.getQueryLocator(query);
    }

    //SEMPRE PROCESSA EM LOTES DE 200 REGISTROS 
 
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        //SET É UMA COLEÇÃO IGUAL A LISTA AONDE NÃO DEIXA REPETIR OS VALORES
        Set<Id> accountIds = new Set<Id>();
        
        for(Property__c propriedade : (List<Property__c>) scope){
            accountIds.add(propriedade.Account__c);
        }

        String[] addresses = new String[]{};
        List<Contact> contatos = [SELECT Id, Email FROM Contact WHERE AccountId IN: accountIds]; 
        for(Contact contato : contatos){
            addresses.add(contato.Email);
        }
        
        new SendEmailService(addresses).sendEmail();
    }
 
    public void finish(Database.BatchableContext bc){
        System.debug('Finalizou!');
    }
 }