force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HouseRepository.cls
public with sharing class HouseRepository implements IRepository{
    
    House__c house;
    String queryString;
    
    public HouseRepository(House__c house, String queryString) {
        this.house = house;
        this.queryString = queryString;
    }

    public Object doQuery(){
        return Database.query(this.queryString);
    }

    public Object doUpsert(){
        try {
            Database.upsert(this.house);
            return true;
        } catch (Exception e) {
            System.debug(e);
            return false; 
        }
    }

    public Object getByMunicipio(String municipio){
        String queryString = 'SELECT Id FROM House__c WHERE Municipio__r.Name = \'' + municipio + '\'';
        return Database.query(queryString);
    }
}