force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdviceService.cls
public with sharing class AdviceService {

    public void getAdviceById(Integer idAdvice){
        Advice_Integration__mdt metadata = [SELECT endPointAdvice__c FROM Advice_Integration__mdt WHERE DeveloperName = 'Advice'];
        String body = new RandomAdviceCallout(metadata.endPointAdvice__c, 13)
                                            .doCallout();
        AdviceTO advice = AdviceTO.parse(body);
        System.debug(advice);
    }

    public void getRandomAdvice(){
        Advice_Integration__mdt metadata = [SELECT endPointAdvice__c FROM Advice_Integration__mdt WHERE DeveloperName = 'Advice'];
        String body = new RandomAdviceCallout(metadata.endPointAdvice__c, null)
                                            .doCallout();
        AdviceTO advice = AdviceTO.parse(body);
        System.debug(advice);
    }

    public Object getProperty(SObject obj){
        String objectName = obj.getSObjectType().getDescribe().getName();
        Object propriedade = Database.query('SELECT Id, Name FROM ' + objectName + ' LIMIT 1');
        System.debug(propriedade);
        return propriedade;
    }
}


Property__c propriedade = new Property__c();
new AdviceService().getProperty(propriedade);


House__c casa = new House__c();
new AdviceService().getProperty(casa);