force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HouseBuilder.cls
public class HouseBuilder extends AbstractHouseBuilder{

    // Construtor
    public HouseBuilder(Id municipioId) {
        super(municipioId);
    }

    // Implementa o método da interface para encadeamento
    override public IHouseBuilder setBeedroms(Decimal beedroms) {
        this.beedroms = beedroms;
        return this;
    }

    override public IHouseBuilder setCep(String cep) {
        this.cep = cep;
        return this;
    }

    override public IHouseBuilder setBathrooms(Decimal bathrooms) {
        this.bathrooms = bathrooms;
        return this;
    }

    
    override public House__c getResult() {
        House__c house = new House__c();
        house.Bedroom__c = this.beedroms;
        house.Bathrooms__c = this.bathrooms;
        house.Cep__c = this.cep;
        house.Municipio__c = this.municipioId;
        return house;
    }
}