force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House__c/fields/SellDate__c.field-meta.xml
<CustomField>
    <fullName>SellDate__c</fullName>
    <label>SellDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Selled__c.field-meta.xml
<CustomField>
    <fullName>Selled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/House__c/fields/SellValue__c.field-meta.xml
<CustomField>
    <fullName>SellValue__c</fullName>
    <label>Sell Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The listed sale price of the home.</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GenerateTestSetup.cls
@isTest
public with sharing class GenerateTestSetup {
    public static House__c createHouse(Integer price, String name){
        House__c house = new House__c(
            Price__c = price,
            Name = name,
            Cep__c = '12345678'
        );
        return house;
    }

    public static House__c createHouseWithAccount(Integer price, String name, Id accId){
        House__c house = new House__c(
            Price__c = price,
            Name = name,
            Cep__c = '12345678',
            Selled__c = true,
            SellDate__c = System.now(),
            SellValue__c = price,
            Account__c = accId
        );

        return house;
    }

    public static Account createAccount(String name){
        Account acc = new Account(Name = name);
        return acc;
    }

    public static Municipio__c createMunicipio(){
        Municipio__c municipio = new Municipio__c(
            Name = 'Goias'
        );
        return municipio;
    }

    public static Property__c createProperty(){
        Property__c property = new Property__c(
            Name = 'Propriedade do Ze'
        );
        return property;
    }

    public static void createSetup(){
        Account acc = createAccount('AccountTest');
        insert acc;

        Municipio__c municipio = createMunicipio();
        insert municipio;

        Property__c property = createProperty();
        insert property;

        House__c house = createHouseWithAccount(500000, 'Nome da Casa', acc.Id);
        house.Municipio__c = municipio.Id;
        house.Property__c = property.Id;
        insert house;

    }
}