force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Houses</relationshipLabel>
    <relationshipName>Houses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/House__c/fields/SellDate__c.field-meta.xml
<CustomField>
    <fullName>SellDate__c</fullName>
    <label>SellDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/House__c/fields/Selled__c.field-meta.xml
<CustomField>
    <fullName>Selled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/House__c/fields/SellValue__c.field-meta.xml
<CustomField>
    <fullName>SellValue__c</fullName>
    <label>Sell Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HouseBO.cls
public with sharing class HouseBO {

    @future
    public static void sendEmailFuture(String[] addresses){
        new SendEmailService(addresses).sendEmail();
    }
    
    public static void setRatingHouseByPrice(List<House__c> triggerNew){
        for(House__c house : triggerNew){
            if(house.Price__c >= 500000){
                house.Rating__c = 'A';
                String[] emails = new String[] {'igor.guedes@fatcursos.org.br'  };
                System.enqueueJob(new SendEmailQueueable(emails));
                sendEmailFuture(emails);
            } else if(house.Price__c >= 300000){
                house.Rating__c = 'B';
            } else {
                house.Rating__c = 'C';
            }
        }
    }


    public static void createOpportunityWhenSelled(List<House__c> triggerNew){
        Map<String, Opportunity> opportunityToInsert = new Map<String, Opportunity>();
        for(House__c house : triggerNew){
            if(house.Selled__c != null && house.SellDate__c != null &&
            house.Opportunity__c == null){
                System.debug('ENTROU NO IF');
                Opportunity opportunity = new Opportunity(
                    Name = house.Name,
                    Amount = house.SellValue__c,
                    StageName = 'Closed Won',
                    CloseDate = Date.valueOf(house.SellDate__c),
                    AccountId = house.Account__c
                );
                opportunityToInsert.put(house.Id, opportunity);
            }    
        }
        System.debug(opportunityToInsert);
        if(!opportunityToInsert.isEmpty()){
            insert opportunityToInsert.values();

            for(House__c house : triggerNew){
                house.Opportunity__c = opportunityToInsert.get(house.Id).Id;
            }
        }

    }
}